# Generated by Django 3.0.2 on 2020-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imortcsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='google',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='google_not_spam',
            field=models.FloatField(max_length=200),
        ),
    ]
